-- mybts»≠∏È

CREATE TABLE tbl_book(
    BOOK_SEQ NUMBER PRIMARY KEY,
    BOOK_ISBN CHAR(13),
    BOOK_TITLE nVARCHAR2(100),
    BOOK_AUTHOR nVARCHAR2(30),
    BOOK_PRICE NUMBER,
    BOOK_DESCRIPTION nVARCHAR2(1000),
    BOOK_IMAGE nVARCHAR2(125),
    BOOK_LINK nVARCHAR2(255),
    BOOK_RENT_YN CHAR(1)
    );


CREATE TABLE tbl_user(
    USER_SEQ NUMBER PRIMARY KEY,
    USER_NAME nVARCHAR2(30),
    USER_BIRTH CHAR(10),
    USER_SEX CHAR(1),
    USER_PHONE nVARCHAR2(15),
    USER_MAIL nVARCHAR2(255),
    USER_IMAGE nVARCHAR2(125),
    USER_REG_DATE CHAR(10),
    USER_OUT_DATE CHAR(10),
    USER_OUT_YN CHAR(1),
    USER_RENT_COUNT NUMBER,
    USER_RENT_TOTAL NUMBER
    );
    
    CREATE TABLE tbl_rent(
    RENT_SEQ NUMBER PRIMARY KEY,
    RENT_DATE CHAR(10),
    RENT_RETURN_DATE CHAR(10),
    
    